RenFORMAT: 1A
HOST: http://paysafe.api.com/alternatepayments/v1/

# Paysafe Alternate Payments API

The Paysafe Alternate Payments API allows you to collect payments from your customers using a
variety of methods.

The API in SAQ (TBD) compliant.

Request and response payloads are formatted as JSON.

# Release Notes

|Version   |Date            |Details|
|---       |---             |---|
|1.3.X     |June  14 2015   |<ul><li>Initial release with support for Ideal, Sofort, Giropay</li></ul>|

# Technical introduction
This section provides a technical introduction to the Paysafe Alternate Payments API. 

## API Endpoints

The Paysafe Alternate Paymenes API is available in the sandbox environment for integration testing purposes. 
To switch between the sandbox and the live production system you only need to change the endpoint URI and the 
credentials.

The following endpoints form the basis of a resource URI:

    Sandbox (Testing) endpoint - https://api.test.paysafe.com/alternatepayments/v1/

    Production endpoint - https://api.paysafe.com/alternatepayments/v1/

As the sandbox environment is completely isolated, any changes you perform on your sandbox accounts configuration
(such as secure IP registration, APP registration) may have to be repeated in your production account.

## Versioning


The API version will influence the request/response object structure as well as the functionality that is available through the API.   A new version of the API will only be introduced if we roll out a backwards incompatible change that may impact your existing integrations.  As your API version can be maintained through the merchant portal, you can manage when to upgrade to the latest version, helping ensure your integration is not disrupted as new functionality becomes available.

### Major Version

The major version \(ie: /v1/ \) represents a major technology shift between versions of the API. Changes in the 
major version are reserved for large scale changes to the API that fundamentally change integration requirements
from the previous version.  Modified business domain models, re-design of functional flows or change in API 
resource patterns are all considered major changes.  Changes to major version are rare and typically require 
an extended deprecation cycle \(~2 years\) from prior versions to allow all consumers of the API to adapt.

> Your integration should take the below backwards compatible changes into consideration so as not to break when additional fields are added to the API.

**What is considered a backwards compatible change?**

* Adding API resources or adding new properties to existing API resources
* Modification to the order of parameters or JSON object elements
* Adding optional request parameters to API methods
* Adding webhook event types

**What is considered a backwards incompatible change?**

* Removal of a API resource
* Removal of an API Resources object attribute
* Changes to required parameter / JSON object elements
* Removal of previously supported API call

***

## Pagination

API calls that return multiple resources will wrap the response as a named JSON array.  For example a collection of 'payment' objects would
be returned as 'payments'. By default, 10 items will be returned at a time and you can navigate to the next set of resources using the 
supplied HATEOAS links.  List responses will also include a meta data section that will identify the number of records included in the collection,
the number of records per page (limit) and current page number.
<br/><br/>
For example, if a request to look up payments identifies that there are 134 payments and you have set your limit to 15, the first 15 items will be returned with navigation links to provide the next 15 items in the list. If you navigate to the next page using the provided HATEOAS link, you will now retrieve items 16-30 with a new navigation link provided to return to the previous page, as well as a link to continue to the next page of items._

> _You can change the default list page size by defining a **limit** parameter value._

|Parameter Name |Description|
|---            |---|
|limit          |The number of records to be returned per page. Default = 10, Max = 100|
|offset         |Identifies your location within the list and allows you to fetch the next set of resources|
|startDate      |This is the start date in UTC. Default value is 30 days before the endDate.|
|endDate        |This is the end date in UTC. Default value is the current date and time.|

Sample Response with List Data

```apib
{
    "payments": [{
        "id": "044e3915-b612-40c7-b652-283bb288521f",
        "merchantRefNum": "xyz",
        "amount": 100,
        "currencyCode": "EUR",
        "profile": {
            "firstName": "Stan",
            "lastName": "Smith",
            "email": "stan.smith@fox.com",
            "ip": "localhost"
        },
        "ideal": {
            "bankName": "ING",
            "accountCountry": "NL"
        },
        "returnLinks": [{
            "rel": "default",
            "href": "http://amazon.com/"
        }],
        "descriptor": "test descriptor",
        "liveMode": true,
        "txnTime": "2016-05-05T20:34:06Z",
        "status": "INITIATED",
        "gatewayResponse": {
            "code": "000.200.000",
            "description": "transaction pending",
            "paymentType": "DB"
        }]
    }],
    "links": [{
        "rel": "self",
        "href": "https://api.paysafe.com/admin/v1/accounts/99000/payments"
    }, {
        "rel": "prev",
        "href": "https://api.paysafe.com/admin/v1/accounts/99000/payments?merchantRefNum=merchantRef_2014_03_10_01&limit=2&offset=2&startDate=2014-03-10T13:01:50Z&endDate=2014-03-20T13:06:50Z"
    }, {
        "rel": "next",
        "href": "https://api.paysafe.com/admin/v1/accounts/99000/payments?merchantRefNum=merchantRef_2014_03_10_01&limit=2&offset=2&startDate=2014-03-10T13:01:50Z&endDate=2014-03-20T13:06:50Z"
    }]
}
```

## Resource Expansion

Resource expansion can be compared to eager loading in the database realm. It offers a way to load a specific resource as well as other resources related to it.  You are encouraged to use resource expansion when you know you are going to need the extra information. This will reduce the amount of API calls as well as the amount of traffic to and from your server. You should avoid resource expansion when you want to reduce the amount of information returned or if you are unsure if you will need the additional resource object.
<br/><br/>
By adding an **expand** query parameter to the query you are effectively telling the server to include the details for the reference object in-line.  Anytime you encounter an object that contains an "_expandable" section, you will know that the resources
identified are expandable. Passing that resource name as part of your expand parameter list will automatically include the associated resource details in your response.
<br/><br/>

For resources that have multiple expandable children, you can specify which resources to expand in a comma separated list. <br />
Eg. <strong>?expand=resource1,resource2</strong>

> Resource Expansion is only available when a single resource is involved.  When you lookup resources that could return collections of results, the _expandable option will not be present.  For example, if you query a payment by a specific payment id, then _expandable will be available if there are related resources such as refunds.  If you query a payment by merchantRefNum, then since a collection of payment resources could be returned, the _expandable option will not show.

<br/>
Below is a sample account lookup. By default the events resource is not expanded and instead includes a 
reference link that would provide the relevant details. If you would rather have the full account object returned, 
then add the **'expand=events'** parameter to your request and you will see the second events returned inline.
<br/>

*Result without resource expansion*

```apib
GET /admin/v1/accounts/<accountId>
{
    "id": "987001112",
    "processorId": "b76786b1-4dfa-4b56-b707-976e47075a61",
    "processorCode": "PAYON",
    "paymentType": "IDEAL",
    "currencyCode": "EUR",
    "status": "ENABLED",
    "creationTime": "2016-04-05T15:17:57Z",
    "lastModificationTime": "2016-04-06T15:24:17Z",
    "allowTestTransaction": false,
    "_expandable": {
        "events": "https://api.paysafe.com/admin/v1/accounts/987001112/events"
    },
    "links": [{
        "rel": "self",
        "href": "https://api.paysafe.com/admin/v1/accounts/987001112"
    }]
}
```

*Result with events expanded*

```apib
GET /admin/v1/accounts/<accountId>?expand=events
{
        "id": "987001112",esource 
        "processorId": "b76786b1-4dfa-4b56-b707-976e47075a61",
        "processorCode": "PAYON",
        "paymentType": "IDEAL",
        "currencyCode": "EUR",
        "status": "ENABLED",
        "creationTime": "2016-04-05T15:17:57Z",
        "lastModificationTime": "2016-04-06T15:24:17Z",
        "allowTestTransaction": false,
        "events": [{
               "id": "deadbeef-aec8-41a5-94d7-446bc3999426",
               "type": "ap_auths_completed"
        }, {
               "id": "6ddbc05a-ff40-4dc1-b2d3-f200934dfdde",
               "type": "ap_auths_declined"
        }, {
               "id": "6ddbc05a-ff40-4dc1-b2d3-f20091234567",
               "type": "ap_refunds_complete"
        }, {
               "id": "12345eef-aec8-41a5-94d7-446bc3999426",
               "type": "ap_refunds_complete"
        }],
        "_expandable": {
            "events": "https://api.paysafe.com/admin/v1/accounts/987001112/events"
        },        
        "links": [{
               "rel": "self",
               "href": "https://api.paysafe.com/admin/v1/accounts/987001112"
        }]
}
```

## HTTP Responses

HTTP response codes are used to indicate the status of a request.

**HTTP Status Code Summary**

|HTTP Response Code Category|Description|
|---|---|
|1xx: Informational|Communicates transfer protocol–level information|
|2xx: Success|Indicates that the client’s request was accepted|
|3xx: Redirection|Indicates that the client must take some additional action in order to complete the request|
|4xx: Client Error|Indicates that the client has made an error with the request|
|5xx: Server Error|Indicates that an error occurred on the server side|

**Common HTTP Response Status Codes**

|HTTP Status Code|Description|
|---|---|
|200 OK|Everything worked as expected|
|201 CREATED|The request was successful. NETBANX created a new resource and the response body contains the representation|
|202 ACCEPTED|This indicates that the client’s request will be handled asynchronously. It tells the client that the request appears valid, but it still may have problems once it is processed|
|204 NO CONTENT|This is usually returned in response to a PUT, POST, or DELETE request, when the REST API declines to send back any status message or representation in the body of the response message|
|304 NOT MODIFIED|The client's cached version of the representation is still up to date|
|400 BAD REQUEST|This often indicates that a required parameter is missing or that a parameter is invalid. This is a generic client-side error status, used when no other 4xx error code is appropriate|
|401 UNAUTHORIZED|This indicates that the client tried to operate on a protected resource without providing the proper authorization. They may have provided the wrong credentials or none at all|
|402 PAYMENT REQUIRED|The parameters were valid but the request failed|
|404 NOT FOUND|The requested resource does not exist|
|405 METHOD NOT ALLOWED|The client tried to POST or PUT to a resource that would not accept it|
|415 UNSUPPORTED MEDIA TYPE|The request is in a format not supported by the requested resource for the requested method|
|429 TOO MANY REQUESTS|The application is sending too many simultaneous requests|
|500 INTERNAL SERVER ERROR|An error occurred with an internal server|
|502 EXTERNAL SERVER ERROR|We received an invalid response from the upstream gateway in attempting to fulfill the request|


## Errors

To ease integration and support for developers 
integrating to our APIs, the error messages that are returned should be verbose enough to correct the problem.  

The error structure contains a 4–5 digit code as well as a human readable message. Additionally, the application 
error code will be returned in the header so it can be easily used by an application without parsing the body.
<br/>

**Error Attributes**

|Element|Type|Description|
|---|---|---|
|Element|Type|Description|
|code|String|This is the error code|
|message|String|This is a description of the error|
|details|Array|This is a detailed description|
|fieldErrors|Array|This is a list of fields that have problems|

**Error message example with details**

```apib
{
    "error": {
        "code": 5023,
        "message": "Bad Request",
        "details": [
            "Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value at  [line: 2, column: 61]"
        ]
    }
}
```
 
 
**Error message example with field errors**

```apib
{
    "error": {
        "code": 5068,
        "message": "Field Error(s)",
        "details": [
            "Either you submitted a request that is missing a mandatory field or the value of a field does not match the format expected."
        ],        
        "fieldErrors": [{
            "field": "recipientEmail",
            "error": "john@hi@you.c.c.c.c is not a valid e-mail address."
        }, {
            "field": "transaction.amount",
            "error": "A transaction amount is required."
        }, {
            "field": "transaction.currency",
            "error": "Currency with value [USD] exceeds the maximum size of [3]."
        }]
    }
}
```


These are the error codes common to all subsystems

|HTTP Status   |Code     |Message                                 |Description|
|---           |---      |---                                     |---|
|400           |5001     |Invalid currency                        |The submitted currency code is invalid or your account does not support this currency.|
|              |5010     |Invalid country                         |The submitted country code is invalid.|
|              |5016     |Account not found                       |The account you provided cannot be found.|
|              |5017     |Account disabled                        |The account you provided is disabled.|
|              |5023     |Bad request                             |The request is not parseable.|
|              |5042     |Invalid merchant reference              |This error usually indicates that a transaction was attempted with the merchant reference field missing. This value is mandatory and must be included with your request.|
|              |5068     |Field error(s)                          |Either you submitted a request that is missing a mandatory  field or the value of a field does not match the format expected.|
|              |5082     |Mode not permitted                      |The request was sent in a mode that is not permitted. For example, a Live refund request was made on a Test authorization request.|
|401           |5275     |Authentication credentials expired      |The authentication credentials provided with the request have expired.|
|              |5276     |Authentication credentials disabled     |The authentication credentials provided with the request provided have been disabled.|
|              |5277     |Authentication credentials locked       |The authentication credentials provided with the request have been locked due to multiple authentication failures.|
|              |5278     |Cannot authenticate                     |The authentication credentials provided with the request were not accepted for an unknown reason.| 
|              |5279     |Authentication credentials are invalid  |The authentication credentials are invalid.|
|              |5280     |Authentication credentials not provided |The required authentication credentials were not provided.|
|403           |5270     |Unauthorized access                     |The credentials provided with the request do not have permission to access the requested data.|
|404           |5269     |Entity not found                        |The ID\(s\) specified in the URL do not correspond to the values in the system.|
|              |5273     |URI not found                           |Your client reached our application but we were unable to service your request due to an invalid URL.|
|405           |5281     |Method not supported                    |The request uses an action (e.g., GET, POST, or PUT) that is not supported by the resource.|
|406           |5271     |Unsupported 'Accept' header             |You requested a response in the 'Accept' header that is in an unsupported format.|
|415           |5272     |Unsupported 'Content-Type'              |The 'Content-Type' you specified in request header was submitted in an unsupported format.|
|429           |1200     |API call rate exceeded                  |The API call has been denied as it has exceeded the permissible call rate limit.|
|500           |1000     |Internal error                          |An internal error occurred.|
|              |1001     |Activity Timed Out                      |Your request timed out before it could be completed.  If you receive this error, it is still possible that your request will be successfully processed and you should use the API to verify the status of your request.|
|              |1002     |Database Error                          |An internal error occurred.|
|              |1003     |Decryption Error                        |An internal error occurred.|
|              |1007     |Gateway Error                           |An internal error occurred.|

These errors are specific to the Alternate Payments API.

|Code                       |Message|                                 
|---                        |---|
|ALTERNATE-PAYMENTS-INT-1   |Gateway Not Provisioned Error|
|ALTERNATE-PAYMENTS-INT-2   |Gateway Authentication Error|
|ALTERNATE-PAYMENTS-INT-3   |Resource not found GatewayService Error|
|ALTERNATE-PAYMENTS-INT-4   |Transaction declined by the Gateway|
|ALTERNATE-PAYMENTS-INT-5   |Auth status not successful|
|ALTERNATE-PAYMENTS-INT-6   |Over refund|
|ALTERNATE-PAYMENTS-INT-7   |Auth expired|
|ALTERNATE-PAYMENTS-INT-8   |Invalid Parameter Gateway Error|
|ALTERNATE-PAYMENTS-INT-9   |Risk Gateway Error|
|ALTERNATE-PAYMENTS-INT-10  |Setup Gateway Error|
|ALTERNATE-PAYMENTS-INT-11  |Gateway Error|
|ALTERNATE-PAYMENTS-INT-12  |Gateway Conditional Success|


## HATEOAS

The Alternate Payments API uses a RESTful endpoint structure and relies on HTTP verbs (GET, PUT, POST, DELETE)
to determine what action you are attempting to perform on a specific resource.

Each API call response includes an array of HATEOAS (Hypermedia as the Engine of Application State) links. 
These links can be used to integrate subsequent flows and typically they will provide you information as to
what you can do next.

By using these links, you no longer need to hardcode your integration to call specific endpoint urls to utilize
our API, but rather can use the returned url for the specific purpose as defined by the 'rel' definition.

#### HATEOAS Link Structure

|Element  |Description|
|---      |---|
|rel      |Link relation that describes how this link relates to the previous call. Examples include self (get details of the current call), parent_payment (get details of the parent payment), or a related call such as execute or refund.|
|href     |URL of the related HATEOAS link you can use for subsequent calls.|


Eg. Below are sample HATEOAS links from a API rsponse that returns a collection of auths. Links
are provided to navigate through the set of resources in the collection.
```
"links": [{
    "rel": "self",
    "href": "https://api.paysafe.com/v1/payments/234243242?limit=10&offset=1"
},  {
    "rel": "prev",
    "href": "https://api.paysafe.com/v1/payments/234243242?limit=10&offset=0"

}, {
    "rel": "next",
    "href": "https://api.paysafe.com/v1/payments/234243242?limit=10&offset=2"
}]

```

## Webhooks



# Payments [/payments]

Description TBD

## Create Payment [POST /accounts/{accountId}/payments]

Your account is setup to allow payments for a specific payment method and currency. 

> Please contact Paysafe Merchant Support to enable additional options for your account.

The following payment methods are supported, if additional attributes are required for the payment method,
see the below table to identify the additional values your should pass as part of your payment request.

|Payment Type  |Additional attributes required |
|---             |---     |
|IDEAL           |Y       | 
|SOFORT          |Y       |
|GIROPAY         |N       |


<table>
<tr><th>Payment Attributes</th><th>Description</th></tr>
<tr bgcolor='#B5F4BA'><td colspan='2'>"ideal": { ... }</td></tr>
<tr><td>ideal.bankName</td><td>The bank name</td></tr>
<tr><td>ideal.accountCurrency</td><td>The currency of the bank account</td></tr>
<tr bgcolor='#B5F4BA'><td colspan='2'>"sofort": { ... }</td></tr>
<tr><td>ideal.bankName</td><td>The bank name</td></tr>
<tr><td>ideal.accountCurrency</td><td>The currency of the bank account</td></tr>
</table>

+ Request Create iDeal payment (application/json)

    + Parameters
        + accountId: `1234567891` (string, required) - Your unique account identifer.

    + Attributes (Ideal Payment)
        + paymentType: `IDEAL` (string, required)
        + Include Payment Request Base

    + Headers
    
            Authorization: Basic YOUR-BASE64-ENCODED-API-KEY
            
+ Response 201 (application/json)

    + Attributes (Ideal Payment)
        + Include Payment Response Base

+ Request Create Sofort payment (application/json)

    + Parameters
        + accountId: `1234567891` (string, required) - Your unique account identifer.

    + Attributes (Sofort Payment)
        + paymentType: `SOFORT` (string, required)    
        + Include Payment Request Base

    + Headers
    
            Authorization: Basic YOUR-BASE64-ENCODED-API-KEY
            
+ Response 201 (application/json)

    + Attributes (Sofort Payment)
        + Include Payment Response Base

+ Request Create Giropay payment (application/json)

    + Parameters
        + accountId: `1234567891` (string, required) - Your unique account identifer.

    + Attributes
        + paymentType: `GIROPAY` (string, required)    
        + Include Payment Request Base

    + Headers
    
            Authorization: Basic YOUR-BASE64-ENCODED-API-KEY

+ Response 201 (application/json)

    + Attributes
        + paymentType: `GIROPAY`
        + Include Payment Response Base
        
## Lookup Payment by paymentId [GET /accounts/{accountId}/payments/{paymentId}]

Returns an individual payment detail.

+ Request (application/json)

+ Response 200 (application/json)

    + Attributes (CUP Payment)
        + Include Payment Response Base

## Lookup Payment by merchantRefNum [GET /accounts/{accountId}/payments/?merchantRefNum={merchantRefNum}]

As merchantRefNum could be used for multiple payments, a collection of payments is returned.

+ Request (application/json)

+ Response 200 (application/json)

    + Attributes
        + payments (array)
            + (Payment Response Base)


# Refunds [/refunds]

## Create Refund [POST /accounts/{accountId}/payments/{paymentId}/refunds]

+ Request (application/json)

    + Parameters
        + accountId: `1234567891` (string, required) - Your unique account identifer.
        + paymentId: `1111111` (string, required) - The unique identifier for the payment.

    + Attributes (Refund Request)

+ Response 201 (application/json)

    + Attributes (Refund Response)


## Lookup Refund by id [GET /accounts/{accountID}/refunds/{id}]

+ Request (application/json)

+ Response 200 (application/json)

    + Attributes (Refund Response)

## Lookup Refund by merchantRefNum [GET /accounts/{accountID}/refunds/?merchantRefNum={merchantRefNum}]

+ Request (application/json)

+ Response 200 (application/json)

    + Attributes
        + refunds (array)
            + (Refund Response)

# Data Structures

## Payment Request Base
+ merchantRefNum: `0b0ceaa3-42ad-442d-b85b-c3b70f24835d` (string, required) - This is the merchant reference number created by the merchant and submitted as part of the request. It must be unique for each request.
+ dupCheck: `true` (boolean, optional) - This validates that this request is not a duplicate. A request is considered a duplicate if the merchantRefNum has already been used in a previous request within the past 90 days.
+ amount: `100` (number, required) - This is the amount of the request, in minor units.
+ descriptor: `Test description` (string, optional) - This is the merchant descriptor that will be displayed on the customer's card statement.
+ Include Profile
+ returnLinks (array) - This is an array of return links.
   + (object) 
        + rel: default
        + href: ...

## Payment Response Base
+ id: `25f6dadf-176a-415f-95c9-6ff39ff697ba` (string, required) - This is the ID returned in the response. This ID can be used for future associated requests, e,g., Settlements.
+ liveMode: `false` (string, required)
+ merchantRefNum: `b0ceaa3-42ad-442d-b85b-c3b70f24835d` (string, required) - This is the merchant reference number created by the merchant and submitted as part of the request.
+ paymentType: `IDEAL`(string, required)
+ dupCheck: `false` (boolean, optional) - This validates that this request is not a duplicate. A request is considered a duplicate if the merchantRefNum has already been used in a previous request within the past 90 days.
+ amount: `100` (number, required) - This is the amount of the request, in minor units.
+ descriptor: `test descriptor` (string, optional) - This is the merchant descriptor that will be displayed on the customer's card statement.
+ txnTime: `2015-12-11T16:33:49Z` (string, required) - This is the date and time the transaction was processed.
+ currencyCode: `EUR` (string, required) - This is the currency of the merchant account, e.g., USD or CAD, returned in the request response.
+ status: `INITIATED` (string, required) - This is the status of the transaction request.
+ Include Profile
+ returnLinks (array) - This is an array of return links.
   + (object) 
        + rel: default
        + href: ...
+ links (array) - This is an array of self-referencing links. 
   + (object) 
        + rel: self
        + href: ...

## Payment Type
+ paymentType (object) - Payment specific parameters

    + One Of
        + `IDEAL`
        + `SOFORT`
        + `GIROPAY`

## Ideal Payment
+ ideal (object) - Parameters required for a iDeal payment request.

    + Properties
        + bankName: `ING` (string, required)
        + accountCountry: `NL` (string, required)
        
## CUP Payment
+ cup (object) - Parameters required for a China Union Pay payment request.

    + Properties
        + bankName: `ING` (string, required)
        + accountCountry: `NL` (string, required)     

## Sofort Payment
+ sofort (object) - Parameters required for a Sofort payment request.

    + Properties
        + productId: `3453453` (string, required)
        + key: `ajklj9alksj98gah4l34jg9` (string, required)

## Profile    
+ profile (object, optional) - These are some details about the customer.

    + Properties
        + firstName: `Stan` (string, required)
        + lastName: `Smith` (string, required)
        + email: `stan.smith@fox.com` (string, required)
        + ip: `127.0.0.1` (string, optional)
        
## Refund Request
+ merchantRefNum: `xyz` (string, optional) - The merchant reference number.
+ dupCheck: `false` (boolean, required) - The duplication check flag.
+ amount: `100` (number, required) - This is the amount in minor units.

## Refund Response
+ id: `6565bce8-9ae2-4359-bc7c-48c2e560810b` (string, required) - The refund id.
+ liveMode: `false` (boolean, required)
+ merchantRefNum: `xyz` (string, required)
+ dupCheck: `true` (boolean, required)
+ amount: `400` (number, required)
+ txnTime: `2016-02-24T08:39:39Z` (string, required)
+ status: `COMPLETED` (string, required)
+ Include Gateway Response

## Gateway Response
+ code: `000.100.110` (string, required)
+ description: `Request successfully processed in 'Merchant in Integrator Test Mode'` (string, required)
+ paymentType: `RF` (string, required)